### ISSUE TITLE
yolov5 version of  sahi sample

### ISSUE THREAD

**Issue by WangRongsheng** [Kazuhito00/sahi-yolox-onnx-sample#1]
Hello,I really appreciate your work.Can you provide the yolov5 version of `sahi-yolox-onnx-sample`？thank you！

**Comment by Kazuhito00** [comment]
Take a look at the Yolo v5 notebook in the original repository.
https://github.com/obss/sahi
https://colab.research.google.com/github/obss/sahi/blob/main/demo/inference_for_yolov5.ipynb
